const seedLeads=[
{id:'L-1001',company:'Nexa Properties',contact:'Rami Haddad',email:'rami@nexa.example',phone:'+971 50 555 1040',service:'Monthly Content',value:12000,stage:'Negotiation',urgency:'Hot',source:'LinkedIn',next:'Today 21:00',notes:'Needs monthly founder-led content and property launch reels.'},
{id:'L-1002',company:'Orbit Events',contact:'Sarah Cole',email:'sarah@orbit.example',phone:'+971 55 204 7731',service:'Event Coverage',value:6500,stage:'Proposal Sent',urgency:'Hot',source:'Event',next:'Tomorrow 10:30',notes:'Two-camera event coverage, same-day highlight reel.'},
{id:'L-1003',company:'Arc Kitchens UAE',contact:'Mariam Al Noor',email:'mariam@arc.example',phone:'+971 52 902 1130',service:'Corporate Videography',value:8500,stage:'Meeting',urgency:'Warm',source:'Instagram',next:'Sep 15',notes:'Brand film plus social cutdowns.'},
{id:'L-1004',company:'Foundry Labs',contact:'James Walker',email:'james@foundry.example',phone:'+971 56 910 1144',service:'Social Content',value:5000,stage:'Contacted',urgency:'Warm',source:'Outbound',next:'Sep 16',notes:'Founder PR content for Dubai expansion.'},
{id:'L-1005',company:'Linea Interiors',contact:'Omar Zain',email:'omar@linea.example',phone:'+971 50 311 9901',service:'Photography',value:3200,stage:'Qualified',urgency:'Warm',source:'Referral',next:'Sep 17',notes:'Interior photography for completed villa.'},
{id:'L-1006',company:'Vertex AI MENA',contact:'Elena Rossi',email:'elena@vertex.example',phone:'+971 58 778 4602',service:'Event Coverage',value:9500,stage:'New Lead',urgency:'Hot',source:'LinkedIn',next:'Today 22:00',notes:'Conference speaker content and executive interviews.'}
];
const services=[['Corporate Videography',3500],['Event Coverage',2500],['Photography',1500],['Social Content',1800],['Video Editing',800],['Monthly Content',6500],['Website Creation',4000],['Branding',2500],['AI Content',1800]];
const proposals=[{id:'P-241',client:'Orbit Events',value:6500,status:'Sent',valid:'Sep 17'},{id:'P-242',client:'Nexa Properties',value:12000,status:'Negotiating',valid:'Sep 18'},{id:'P-238',client:'Linea Interiors',value:3200,status:'Draft',valid:'Sep 20'}];
const projects=[{client:'Aster Hospitality',name:'Autumn Campaign Film',status:'Editing',deadline:'Sep 18',value:7800},{client:'Kinetic Expo',name:'Conference Coverage',status:'Pre-production',deadline:'Sep 22',value:9200},{client:'Northline Studio',name:'Monthly Reels',status:'Active',deadline:'Ongoing',value:6500}];
const defaultTasks=[{text:'Call Rami at Nexa Properties',due:'Today 21:00',done:false},{text:'Follow up Orbit Events proposal',due:'Tomorrow 10:30',done:false},{text:'Prepare shot list for Kinetic Expo',due:'Sep 16',done:false},{text:'Send delivery link to Aster Hospitality',due:'Sep 18',done:false}];
let leads=JSON.parse(localStorage.getItem('ainx-leads')||'null')||seedLeads;
let tasks=JSON.parse(localStorage.getItem('ainx-tasks')||'null')||defaultTasks;
const stages=['New Lead','Qualified','Contacted','Meeting','Proposal Sent','Negotiation','Won'];
const money=n=>new Intl.NumberFormat('en-AE',{style:'currency',currency:'AED',maximumFractionDigits:0}).format(n);
const qs=s=>document.querySelector(s),qsa=s=>[...document.querySelectorAll(s)];
function persist(){localStorage.setItem('ainx-leads',JSON.stringify(leads));localStorage.setItem('ainx-tasks',JSON.stringify(tasks));}
function toast(t){const el=qs('#toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function metric(label,value,delta){return `<div class="metric"><div class="label">${label}</div><div class="value">${value}</div><div class="delta">${delta}</div></div>`}
function renderDashboard(){const active=leads.filter(l=>!['Won','Lost'].includes(l.stage));const won=leads.filter(l=>l.stage==='Won').reduce((a,b)=>a+b.value,0);const pipeline=active.reduce((a,b)=>a+b.value,0);qs('#metrics').innerHTML=[metric('Active opportunities',active.length,'Live pipeline'),metric('Pipeline value',money(pipeline),'Across all open stages'),metric('Proposals sent',leads.filter(l=>l.stage==='Proposal Sent').length,'Ready for follow-up'),metric('Won revenue',money(won||15600),'Current workspace total')].join('');
qs('#funnel').innerHTML=stages.slice(0,6).map(s=>{const arr=leads.filter(l=>l.stage===s);return `<div class="funnel-step"><span>${s}</span><b>${arr.length}</b><small>${money(arr.reduce((a,b)=>a+b.value,0))}</small></div>`}).join('');
qs('#priorityRows').innerHTML=leads.filter(l=>l.urgency==='Hot'||['Proposal Sent','Negotiation'].includes(l.stage)).slice(0,5).map(rowHTML).join('');
const hot=leads.filter(l=>l.urgency==='Hot'&&!['Won','Lost'].includes(l.stage));qs('#agentSuggestions').innerHTML=(hot.length?hot.slice(0,3):leads.slice(0,3)).map((l,i)=>`<div class="agent-item"><strong>${i===0?'Call now':'Follow up'} · ${l.company}</strong>${l.stage} · ${money(l.value)}. ${l.notes}</div>`).join('');
qs('#todayTasks').innerHTML=tasks.filter(t=>!t.done).slice(0,4).map(t=>`<div class="task-mini"><strong>${t.text}</strong><span>${t.due}</span></div>`).join('')}
function rowHTML(l){return `<tr><td><strong>${l.company}</strong><br><span style="color:var(--muted)">${l.contact}</span></td><td>${l.service}</td><td>${money(l.value)}</td><td><span class="badge">${l.stage}</span></td><td><span class="badge ${l.urgency==='Hot'?'hot':''}">${l.urgency}</span></td><td>${l.next||'Not set'}</td></tr>`}
function renderLeads(){const f=qs('#leadFilter')?.value||'all';const data=f==='all'?leads:leads.filter(l=>l.stage===f);qs('#leadRows').innerHTML=data.map(l=>`<tr><td><strong>${l.company}</strong><br><span style="color:var(--muted)">${l.contact}</span></td><td>${l.service}</td><td>${money(l.value)}</td><td><select class="stage-select" data-id="${l.id}">${stages.concat('Lost').map(s=>`<option ${s===l.stage?'selected':''}>${s}</option>`).join('')}</select></td><td><span class="badge ${l.urgency==='Hot'?'hot':''}">${l.urgency}</span></td><td>${l.next||'Not set'}</td><td><button class="text-btn delete-lead" data-id="${l.id}">Remove</button></td></tr>`).join('');qsa('.stage-select').forEach(x=>x.onchange=e=>{const l=leads.find(v=>v.id===e.target.dataset.id);l.stage=e.target.value;persist();renderAll();toast('Pipeline updated')});qsa('.delete-lead').forEach(x=>x.onclick=e=>{leads=leads.filter(v=>v.id!==e.target.dataset.id);persist();renderAll();toast('Lead removed')})}
function renderKanban(){qs('#kanban').innerHTML=stages.map(s=>{const items=leads.filter(l=>l.stage===s);return `<div class="kanban-col"><div class="kanban-title"><b>${s}</b><span>${items.length}</span></div>${items.map(l=>`<div class="deal-card"><strong>${l.company}</strong><p>${l.contact} · ${l.service}</p><b>${money(l.value)}</b><p>${l.next||''}</p></div>`).join('')}</div>`}).join('')}
function renderContacts(){qs('#contactCards').innerHTML=leads.slice(0,9).map(l=>`<div class="contact-card"><div class="eyebrow">${l.company}</div><h3>${l.contact}</h3><p>${l.email}</p><p>${l.phone}</p><span class="badge">${l.source}</span></div>`).join('')}
function renderOutreach(){qs('#outreachLead').innerHTML=leads.map(l=>`<option value="${l.id}">${l.company} — ${l.contact}</option>`).join('')}
function renderProposals(){qs('#proposalCards').innerHTML=proposals.map(p=>`<div class="proposal-card"><div class="eyebrow">${p.id}</div><h3>${p.client}</h3><p>${money(p.value)}</p><span class="badge">${p.status}</span><p style="color:var(--muted);font-size:12px">Valid until ${p.valid}</p></div>`).join('')}
function renderProjects(){qs('#projectCards').innerHTML=projects.map(p=>`<div class="project-card"><div class="eyebrow">${p.client}</div><h3>${p.name}</h3><p>${money(p.value)}</p><span class="badge">${p.status}</span><p style="color:var(--muted);font-size:12px">Deadline: ${p.deadline}</p></div>`).join('')}
function renderTasks(){qs('#taskList').innerHTML=tasks.map((t,i)=>`<div class="task-row ${t.done?'done':''}"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}><div><strong>${t.text}</strong><div style="color:var(--muted);font-size:11px">${t.due}</div></div><button class="text-btn task-delete" data-task="${i}">Delete</button></div>`).join('');qsa('[data-task][type=checkbox]').forEach(x=>x.onchange=e=>{tasks[+e.target.dataset.task].done=e.target.checked;persist();renderAll()});qsa('.task-delete').forEach(x=>x.onclick=e=>{tasks.splice(+e.target.dataset.task,1);persist();renderAll()})}
function countsBy(key){return leads.reduce((a,l)=>(a[l[key]]=(a[l[key]]||0)+1,a),{})}
function bars(data){const max=Math.max(...Object.values(data),1);return Object.entries(data).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="bar-line"><span>${k}</span><div class="bar"><span style="width:${v/max*100}%"></span></div><b>${v}</b></div>`).join('')}
function renderAnalytics(){const total=leads.reduce((a,b)=>a+b.value,0),hot=leads.filter(l=>l.urgency==='Hot').length;qs('#analyticsMetrics').innerHTML=[metric('CRM value',money(total),'All tracked opportunities'),metric('Hot leads',hot,'Highest priority'),metric('Average deal',money(Math.round(total/Math.max(leads.length,1))),'Current average'),metric('Lead volume',leads.length,'Stored locally')].join('');qs('#sourceBars').innerHTML=bars(countsBy('source'));qs('#serviceBars').innerHTML=bars(countsBy('service'))}
function renderSettings(){qs('#serviceSettings').innerHTML=services.map(([n,p])=>`<label>${n}<input type="number" value="${p}"></label>`).join('')}
function renderAll(){renderDashboard();renderLeads();renderKanban();renderContacts();renderOutreach();renderProposals();renderProjects();renderTasks();renderAnalytics();renderSettings()}
function openLead(){qs('#leadModal').classList.add('open')}function closeLead(){qs('#leadModal').classList.remove('open')}
['#newLeadBtn','#heroLeadBtn','#leadPageAdd','#pipelineAdd'].forEach(id=>qs(id).onclick=openLead);qsa('.close-modal').forEach(x=>x.onclick=closeLead);
qs('#leadForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));leads.unshift({id:'L-'+Date.now(),company:d.company,contact:d.contact,email:d.email,phone:d.phone,service:d.service,value:+d.value||0,stage:'New Lead',urgency:d.urgency,source:d.source,next:'Not set',notes:d.notes});persist();renderAll();e.target.reset();closeLead();toast('New lead added')};
qsa('.nav-item').forEach(btn=>btn.onclick=()=>showView(btn.dataset.view));qsa('[data-jump]').forEach(btn=>btn.onclick=()=>showView(btn.dataset.jump));function showView(v){qsa('.view').forEach(x=>x.classList.remove('active'));qs(`#${v}-view`).classList.add('active');qsa('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===v));qs('#pageTitle').textContent={dashboard:'Command Center',leads:'Lead Database',pipeline:'Deal Pipeline',contacts:'Contacts',outreach:'Outreach Studio',proposals:'Proposals',projects:'Projects',tasks:'Tasks',analytics:'Analytics',settings:'Settings'}[v];qs('#sidebar').classList.remove('open')}
qs('#leadFilter').onchange=renderLeads;qs('#menuBtn').onclick=()=>qs('#sidebar').classList.toggle('open');qs('#themeBtn').onclick=()=>document.body.classList.toggle('light');
qs('#generateMessage').onclick=()=>{const l=leads.find(x=>x.id===qs('#outreachLead').value);const channel=qs('#outreachChannel').value,goal=qs('#outreachGoal').value;const msg=`Hi ${l.contact},\n\nI’m Ullas from Ainfilms in Dubai. I came across ${l.company} and thought there may be a strong fit around ${l.service.toLowerCase()}. We help brands create premium visual content with a fast production workflow built for UAE campaigns.\n\nFor ${goal.toLowerCase()}, I can share a focused concept and scope based on what ${l.company} is working on now. Would a quick 10-minute call this week be useful?\n\nBest,\nUllas P Murali\nAinfilms`;qs('#messageOutput').value=msg;toast(`${channel} draft generated`)};qs('#copyMessage').onclick=()=>{navigator.clipboard?.writeText(qs('#messageOutput').value);toast('Draft copied')};
qs('#taskAdd').onclick=()=>{const text=prompt('Task');if(text){tasks.unshift({text,due:'Today',done:false});persist();renderAll();toast('Task added')}};qs('#proposalAdd').onclick=()=>toast('Proposal builder ready for next integration');qs('#projectAdd').onclick=()=>toast('Project creation ready for next integration');
qs('#quickAgentBtn').onclick=()=>qs('#agentModal').classList.add('open');qsa('.close-agent').forEach(x=>x.onclick=()=>qs('#agentModal').classList.remove('open'));function agentReply(q){const hot=leads.filter(l=>l.urgency==='Hot'&&!['Won','Lost'].includes(l.stage)).sort((a,b)=>b.value-a.value);if(/call|first|priority|hot/i.test(q)&&hot[0])return `Start with ${hot[0].contact} at ${hot[0].company}. It is a ${money(hot[0].value)} ${hot[0].stage.toLowerCase()} opportunity marked Hot. Next move: reference “${hot[0].notes}” and ask for a concrete decision or meeting time.`;if(/pipeline|value|revenue/i.test(q))return `Your open pipeline is ${money(leads.filter(l=>!['Won','Lost'].includes(l.stage)).reduce((a,b)=>a+b.value,0))} across ${leads.filter(l=>!['Won','Lost'].includes(l.stage)).length} active opportunities.`;return `I’d focus on the Hot leads first, then every Proposal Sent or Negotiation deal. You currently have ${hot.length} Hot opportunities. Ask me “which lead should I call first?” for a specific recommendation.`}
qs('#agentSend').onclick=()=>{const input=qs('#agentInput'),q=input.value.trim();if(!q)return;qs('#agentChat').insertAdjacentHTML('beforeend',`<div class="user-msg">${q}</div><div class="bot-msg">${agentReply(q)}</div>`);input.value='';qs('#agentChat').scrollTop=99999};qs('#agentInput').addEventListener('keydown',e=>{if(e.key==='Enter')qs('#agentSend').click()});
qs('#globalSearch').oninput=e=>{const q=e.target.value.toLowerCase();if(!q)return;const l=leads.find(x=>(x.company+' '+x.contact+' '+x.service).toLowerCase().includes(q));if(l)toast(`Found: ${l.company} · ${l.stage}`)};
renderAll();