import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],cl=(v,a,b)=>Math.max(a,Math.min(b,v)),R=(a,b)=>a+Math.random()*(b-a);
const D=[
{id:'downtown',name:'Downtown Dubai',kicker:'DUBAI · GOLDEN HOUR',desc:'Iconic skyline, promenades and a cinematic place to begin.',fare:0,mode:'START',pos:[67,38],c:['#3d4b55','#11181c']},
{id:'deira',name:'Deira',kicker:'CREEK · HERITAGE',desc:'Souks, creek air and older Dubai street rhythm.',fare:3,mode:'BUS',pos:[29,27],c:['#725b45','#191614']},
{id:'alseef',name:'Al Seef',kicker:'CREEK · OLD DUBAI',desc:'Stone alleys, waterfront paths and abra movement.',fare:2,mode:'ABRA',pos:[40,44],c:['#6b5a48','#172127']},
{id:'businessbay',name:'Business Bay',kicker:'CANAL · CITY',desc:'Glass towers, canal edges and business district energy.',fare:3,mode:'BUS',pos:[61,50],c:['#40535d','#10181d']},
{id:'jumeirah',name:'Jumeirah',kicker:'COAST · BEACH',desc:'Beach roads, palms, villas and open Gulf light.',fare:5,mode:'BUS',pos:[54,68],c:['#527d83','#172423']},
{id:'marina',name:'Dubai Marina',kicker:'MARINA · BLUE HOUR',desc:'High-rise waterfront, promenade reflections and city lights.',fare:5,mode:'METRO',pos:[79,76],c:['#314c61','#10161c']},
{id:'expo',name:'Expo City Dubai',kicker:'EXPO · FUTURE',desc:'Large plazas, shade structures and modern architecture.',fare:6,mode:'METRO',pos:[37,82],c:['#4a5258','#171a1d']}];
const M=[['First Steps',3,'Collect 3 finds',5,'collect'],['Dubai Pocket',100,'Reach 100 points',8,'score'],['City Hopper',3,'Visit 3 districts',10,'visited'],['Collector',12,'Collect 12 finds',15,'collect']];
const st=JSON.parse(localStorage.getItem('md-save')||'null')||{points:0,balance:25,current:'downtown',visited:['downtown'],collected:{},count:0,mission:0,night:false};
const save=()=>localStorage.setItem('md-save',JSON.stringify(st)),aed=v=>'AED '+Number(v).toFixed(2);
let scene,camera,renderer,world,clock,sun,hemi,items=[],cars=[],walls=[],started=false,drag=false,lx=0,ly=0,yaw=0,pitch=-.05,jx=0,jy=0,photo=false;
const keys={},player=new THREE.Vector3(0,1.72,9),vel=new THREE.Vector3();
function mat(c,r=.8,m=0){return new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m})}
function mesh(g,m,x,y,z){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;world.add(o);return o}
function box(w,h,d,c,x,y,z){return mesh(new THREE.BoxGeometry(w,h,d),mat(c,.65,.08),x,y,z)}
function ground(c='#aaa397'){const o=mesh(new THREE.PlaneGeometry(160,160),mat(c,.95),0,0,0);o.rotation.x=-Math.PI/2;o.castShadow=false}
function road(z=0){const o=mesh(new THREE.PlaneGeometry(16,160),mat('#34383b',.96),0,.018,z);o.rotation.x=-Math.PI/2;o.castShadow=false;for(let zz=-70;zz<70;zz+=12)box(.18,.02,5,'#d7ca9a',0,.035,zz+z)}
function building(x,z,w,d,h,c='#87969b'){box(w,h,d,c,x,h/2,z);walls.push({x,z,wx:w/2+.6,wz:d/2+.6});for(let y=3;y<h-1;y+=4)for(const sx of [-1,1]){const win=box(.04,1.8,Math.max(1,d*.55),'#1c2b32',x+sx*(w/2+.03),y,z);win.material.metalness=.35}}
function palm(x,z,s=1){const t=mesh(new THREE.CylinderGeometry(.16*s,.25*s,5*s,8),mat('#76583b',1),x,2.5*s,z);const leaf=mat('#315c41',.9);for(let i=0;i<8;i++){const l=mesh(new THREE.PlaneGeometry(.55*s,3*s),leaf,x,5.1*s,z);l.material.side=THREE.DoubleSide;l.rotation.set(-.25,i/8*Math.PI*2,0);l.translateY(1*s)}}
function label(txt,fg='#141719',bg='#edd99c',w=.8,h=.34){const c=document.createElement('canvas');c.width=256;c.height=96;const g=c.getContext('2d');g.fillStyle=bg;g.fillRect(0,0,256,96);g.fillStyle=fg;g.font='700 48px Arial';g.textAlign='center';g.textBaseline='middle';g.fillText(txt,128,50);const t=new THREE.CanvasTexture(c);return new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({map:t,side:THREE.DoubleSide}))}
function collect(x,z,v){const g=new THREE.Group(),b=new THREE.Mesh(new THREE.CylinderGeometry(.44,.5,.18,18),mat('#c9c8bd',.28,.7));b.position.y=.25;g.add(b);const q=new THREE.Mesh(new THREE.SphereGeometry(.28,16,12),new THREE.MeshStandardMaterial({color:'#f1dda1',emissive:'#c99f48',emissiveIntensity:2}));q.position.y=.5;g.add(q);const l=label(String(v));l.position.y=1;g.add(l);g.position.set(x,0,z);world.add(g);items.push({g,v,key:st.current+':'+x+':'+z,taken:false,p:Math.random()*6})}
function bus(x,z,dir=1,route='F13'){const g=new THREE.Group(),body=new THREE.Mesh(new THREE.BoxGeometry(2.5,2.6,8),mat('#e7e7e3',.42,.18));body.position.y=1.7;g.add(body);const stripe=new THREE.Mesh(new THREE.BoxGeometry(2.55,.32,7.9),mat('#8f333b',.6));stripe.position.y=1.05;g.add(stripe);const glass=mat('#172830',.2,.35);for(const sx of [-1.27,1.27])for(let z2=-2.6;z2<3;z2+=1.4){const w=new THREE.Mesh(new THREE.BoxGeometry(.03,.92,1.05),glass);w.position.set(sx,2.06,z2);g.add(w)}const s=label(route,'#16191b','#e8ad47',1,.3);s.position.set(0,2.52,-4.02);s.rotation.y=Math.PI;g.add(s);g.position.set(x,0,z);g.rotation.y=dir<0?Math.PI:0;world.add(g);cars.push({g,v:dir*4.2})}
function car(x,z,dir=1,c='#dedede'){const g=new THREE.Group(),a=new THREE.Mesh(new THREE.BoxGeometry(1.65,.62,3.5),mat(c,.4,.3));a.position.y=.58;g.add(a);const b=new THREE.Mesh(new THREE.BoxGeometry(1.35,.58,1.8),mat('#17262e',.2,.4));b.position.set(0,1.08,-.1);g.add(b);g.position.set(x,0,z);world.add(g);cars.push({g,v:dir*R(5,7)})}
function water(x,z,w,d){const o=mesh(new THREE.PlaneGeometry(w,d),new THREE.MeshPhysicalMaterial({color:'#356a79',roughness:.22,metalness:.15,transparent:true,opacity:.88}),x,.025,z);o.rotation.x=-Math.PI/2}
function city(id){ground(id==='deira'||id==='jumeirah'?'#c4aa7d':'#a7a5a0');if(id!=='alseef'&&id!=='marina'&&id!=='expo')road(id==='businessbay'?-20:id==='jumeirah'?-13:0);
if(id==='downtown'){building(-28,-25,15,13,42);building(28,-30,16,14,55);building(-30,28,18,15,34,'#988f85');for(let i=0;i<6;i++)building(14+i*2.1,48+i,2.3,2.6,22+i*i*4,'#9ba5a7');water(0,-52,38,14);bus(-4,-68,1,'F13');car(4,-30,1);for(let z=-60;z<60;z+=17){palm(-18,z,.8);palm(18,z+7,.8)}}
if(id==='deira'){road(-4);for(let x=-52;x<=52;x+=18){building(x,-30,13,12,R(9,18),'#b7a688');building(x,32,14,12,R(9,17),'#bfae90')}for(let i=0;i<8;i++)box(7,2.4,4,i%2?'#75503c':'#8a6c47',-46+i*13,1.2,8);bus(4,-68,1,'C01');car(-4,15,-1,'#d7d0c6')}
if(id==='alseef'){water(31,0,42,160);for(let z=-65;z<=65;z+=18){building(-27,z,15,12,R(7,14),'#ae9a7d');palm(-8,z,.7)}}
if(id==='businessbay'){water(25,8,28,160);for(let z=-65;z<=65;z+=22){building(-28,z,15,15,R(35,70));building(48,z+8,14,15,R(32,66))}bus(-4,-68,1,'F20');car(4,-18,1)}
if(id==='jumeirah'){water(43,0,60,160);for(let z=-65;z<=65;z+=22){building(-36,z,15,17,R(7,12),'#d1c8b6');palm(-5,z,.9);palm(7,z+7,.85)}bus(-3,-68,1,'88A')}
if(id==='marina'){water(0,0,24,160);for(let z=-65;z<=65;z+=19){building(-29,z,14,14,R(38,78),'#77878d');building(30,z+8,14,14,R(42,88),'#8c999d');palm(-12,z,.62);palm(12,z+7,.62)}}
if(id==='expo'){const dome=new THREE.Mesh(new THREE.SphereGeometry(18,24,12,0,Math.PI*2,0,Math.PI/2),new THREE.MeshStandardMaterial({color:'#9aa3a5',wireframe:true,metalness:.5}));dome.position.set(20,0,18);dome.scale.y=.7;world.add(dome);for(let a=0;a<Math.PI*2;a+=Math.PI/7)building(Math.cos(a)*48,Math.sin(a)*48,10,10,R(9,17),'#9da5a4')}
const spots={downtown:[[-11,-11,10],[10,15,20],[22,-4,5],[-24,44,50],[17,36,10],[-20,-51,20],[6,-44,5]],deira:[[-18,10,10],[19,8,20],[-32,-8,5],[34,-15,20],[42,18,50],[-47,21,10]],alseef:[[-8,-32,10],[-13,3,5],[-9,27,20],[-35,43,50],[-42,-48,20]],businessbay:[[-16,-5,5],[5,-8,10],[8,25,20],[-20,39,50],[7,58,10]],jumeirah:[[-6,-35,5],[11,-21,10],[13,17,20],[-8,34,10],[-26,47,50]],marina:[[-10,-41,5],[10,-30,20],[-11,-8,10],[11,15,10],[-10,42,50]],expo:[[-7,-42,5],[9,-31,10],[-20,-15,20],[5,8,10],[-29,28,50]]};(spots[id]||spots.downtown).forEach(a=>collect(...a))}
function clear(){if(world)scene.remove(world);world=new THREE.Group();scene.add(world);items=[];cars=[];walls=[]}
function load(id,first=false){st.current=id;if(!st.visited.includes(id))st.visited.push(id);save();clear();city(id);items.forEach(o=>{if(st.collected[o.key]){o.taken=true;o.g.visible=false}});player.set(0,1.72,9);vel.set(0,0,0);yaw=0;pitch=-.05;update();travelUI();mapUI();mission();if(!first)toast('Arrived · '+D.find(d=>d.id===id).name)}
function update(){const d=D.find(x=>x.id===st.current);$('#points').textContent=st.points;$('#balance').textContent=aed(st.balance);$('#bootPoints').textContent=st.points;$('#bootBalance').textContent=aed(st.balance);$('#districtKicker').textContent=d.kicker;$('#districtName').textContent=d.name;$('#districtDesc').textContent=d.desc;$('#photoLabel').textContent=d.name.toUpperCase()+' · '+(st.night?'21:48':'18:42');const m=M[Math.min(st.mission,M.length-1)],p=m?(m[4]==='score'?st.points:m[4]==='visited'?st.visited.length:st.count):0;$('#missionTitle').textContent=st.mission>=M.length?'Dubai Regular':m[0];$('#missionProgress').textContent=st.mission>=M.length?'All starter missions complete':m[2]+' · '+Math.min(p,m[1])+'/'+m[1]}
function mission(){if(st.mission>=M.length)return;const m=M[st.mission],p=m[4]==='score'?st.points:m[4]==='visited'?st.visited.length:st.count;if(p>=m[1]){st.balance+=m[3];st.mission++;save();update();toast('Mission complete · +AED '+m[3]);setTimeout(mission,250)}}
function travelUI(){$('#travelGrid').innerHTML=D.map(d=>'<button class="travel-card '+(d.id===st.current?'current':'')+'" style="--a:'+d.c[0]+';--b:'+d.c[1]+'" data-d="'+d.id+'" '+(d.id!==st.current&&st.balance<d.fare?'disabled':'')+'><span>'+d.mode+' · '+(d.id===st.current?'YOU ARE HERE':aed(d.fare))+'</span><h4>'+d.name+'</h4><p>'+d.desc+'</p><div class="travel-meta"><b>'+(st.visited.includes(d.id)?'VISITED':'NEW DISTRICT')+'</b><b>'+(d.id===st.current?'CURRENT':'GO ↗')+'</b></div></button>').join('');$$('[data-d]').forEach(b=>b.onclick=()=>{const d=D.find(x=>x.id===b.dataset.d);if(d.id===st.current)return close('travelModal');if(st.balance<d.fare)return toast('Not enough travel balance');st.balance-=d.fare;save();close('travelModal');$('#loader').classList.remove('hidden');setTimeout(()=>{load(d.id);$('#loader').classList.add('hidden')},400)})}
function mapUI(){$('#mapBoard').innerHTML=D.map(d=>'<button class="map-node '+(d.id===st.current?'current':st.visited.includes(d.id)?'visited':'')+'" style="left:'+d.pos[0]+'%;top:'+d.pos[1]+'%"><i></i><span>'+d.name+'</span></button>').join('')}
function open(id){$('#'+id).classList.add('open')}function close(id){$('#'+id).classList.remove('open')}function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.x);toast.x=setTimeout(()=>e.classList.remove('show'),1600)}
function bind(){addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='KeyM')open('mapModal');if(e.code==='KeyC')photoMode();if(e.code==='KeyN'){st.night=!st.night;save();light()}});addEventListener('keyup',e=>keys[e.code]=0);$('#world').onpointerdown=e=>{if(!started)return;drag=true;lx=e.clientX;ly=e.clientY};addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-lx)*.003;pitch=cl(pitch-(e.clientY-ly)*.0025,-.8,.45);lx=e.clientX;ly=e.clientY});$('#startBtn').onclick=()=>{started=true;$('#boot').classList.add('hidden');toast('WASD to move · drag to look')};$('#travelBtn').onclick=()=>open('travelModal');$('#mapBtn').onclick=()=>open('mapModal');$('#cameraBtn').onclick=photoMode;$('#featureBtn').onclick=$('#featureBtnBoot').onclick=()=>open('featureModal');$$('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));$('#saveFeatureBtn').onclick=()=>{const t=$('#featureText').value.trim();if(!t)return toast('Write a request first');const a=JSON.parse(localStorage.getItem('md-features')||'[]');a.push(t);localStorage.setItem('md-features',JSON.stringify(a));$('#featureText').value='';close('featureModal');toast('Feature request saved')};$('#mobileCamera').onclick=photoMode;$('#mobileMap').onclick=()=>open('mapModal');$('#mobileTravel').onclick=()=>open('travelModal');const j=$('#joystick'),s=$('#stick');let act=false;const mv=e=>{if(!act)return;const p=e.touches[0],r=j.getBoundingClientRect();let x=p.clientX-r.left-44,y=p.clientY-r.top-44,L=Math.hypot(x,y),mx=28;if(L>mx){x=x/L*mx;y=y/L*mx}s.style.transform='translate('+x+'px,'+y+'px)';jx=x/mx;jy=-y/mx};j.ontouchstart=e=>{act=true;mv(e)};j.ontouchmove=mv;j.ontouchend=()=>{act=false;jx=jy=0;s.style.transform=''}}function photoMode(){photo=!photo;$('#photoFrame').classList.toggle('active',photo);if(photo){$('#photoFlash').classList.add('fire');setTimeout(()=>$('#photoFlash').classList.remove('fire'),320)}}function light(){scene.background.set(st.night?'#16232b':'#88979b');scene.fog.color.set(st.night?'#18262d':'#aaa59c');sun.intensity=st.night?.4:3.8;hemi.intensity=st.night?.55:1.1;renderer.toneMappingExposure=st.night?.75:1.05}
function loop(){requestAnimationFrame(loop);const dt=Math.min(clock.getDelta(),.04),t=clock.elapsedTime;if(started&&!$('.modal.open')){const f=(keys.KeyW||keys.ArrowUp?1:0)-(keys.KeyS||keys.ArrowDown?1:0)+jy,s=(keys.KeyD||keys.ArrowRight?1:0)-(keys.KeyA||keys.ArrowLeft?1:0)+jx,dir=new THREE.Vector3(s,0,-f);if(dir.lengthSq())dir.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),yaw);vel.lerp(dir.multiplyScalar(keys.ShiftLeft?8:5.2),Math.min(1,dt*7));const n=player.clone().addScaledVector(vel,dt);n.x=cl(n.x,-73,73);n.z=cl(n.z,-73,73);let hit=false;for(const w of walls)if(Math.abs(n.x-w.x)<w.wx&&Math.abs(n.z-w.z)<w.wz)hit=true;if(!hit)player.copy(n);camera.parent.position.copy(player);camera.parent.rotation.y=yaw;camera.rotation.x=pitch}for(const o of items){if(o.taken)continue;o.g.rotation.y=t*.7+o.p;o.g.position.y=Math.sin(t*1.7+o.p)*.1;if(player.distanceTo(new THREE.Vector3(o.g.position.x,1.72,o.g.position.z))<2){o.taken=true;o.g.visible=false;st.collected[o.key]=1;st.points+=o.v;st.balance+=Math.max(.25,o.v*.025);st.count++;save();update();mission();travelUI();const p=$('#collectPop');p.textContent='+'+o.v;p.classList.remove('show');void p.offsetWidth;p.classList.add('show')}}for(const c of cars){c.g.position.z+=c.v*dt;if(c.g.position.z>82)c.g.position.z=-82;if(c.g.position.z<-82)c.g.position.z=82}renderer.render(scene,camera)}
renderer=new THREE.WebGLRenderer({canvas:$('#world'),antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.outputColorSpace=THREE.SRGBColorSpace;scene=new THREE.Scene();scene.fog=new THREE.FogExp2('#aaa59c',.0085);camera=new THREE.PerspectiveCamera(68,innerWidth/innerHeight,.08,380);const rig=new THREE.Object3D();rig.add(camera);scene.add(rig);hemi=new THREE.HemisphereLight('#dfe9ec','#806f5b',1.1);scene.add(hemi);sun=new THREE.DirectionalLight('#ffd9a8',3.8);sun.position.set(-40,70,-30);sun.castShadow=true;scene.add(sun);clock=new THREE.Clock();bind();load(st.current,true);light();setTimeout(()=>$('#loader').classList.add('hidden'),450);loop();